// tests/test_Mo2Importer.cpp
#include <QtTest>
#include <QTemporaryDir>
#include <QFile>
#include <QDir>
#include "import/Mo2Importer.h"
#include "core/Types.h"
#include "core/Profile.h"
#include "core/ProfileManager.h"
using namespace solero;
static void write(const QString& p, const QString& c){ QDir().mkpath(QFileInfo(p).path()); QFile f(p); f.open(QIODevice::WriteOnly); f.write(c.toUtf8()); }

class TestMo2Importer : public QObject { Q_OBJECT
private slots:
    void parsesOrderEnabledAndSeparators() {
        // MO2 order (top=highest). Reversed for Solero (index0=lowest).
        QString txt =
            "# This file was automatically generated by Mod Organizer.\n"
            "+High Priority Mod\n"
            "-Disabled Mod\n"
            "+Textures_separator\n"
            "+Low Priority Mod\n"
            "*Unmanaged Thing\n";
        auto entries = Mo2Importer::parseModlist(txt);
        // Reversed, *Unmanaged + comment dropped. Expect (low->high):
        // [Low Priority Mod], [Textures separator], [Disabled Mod(disabled)], [High Priority Mod]
        QCOMPARE(entries.size(), 4);
        QCOMPARE(entries[0].name, QString("Low Priority Mod"));
        QCOMPARE(entries[0].type, EntryType::Mod);
        QCOMPARE(entries[1].type, EntryType::Separator);
        QCOMPARE(entries[1].name, QString("Textures"));
        QCOMPARE(entries[2].name, QString("Disabled Mod"));
        QCOMPARE(entries[2].enabled, false);
        QCOMPARE(entries[3].name, QString("High Priority Mod"));
        QCOMPARE(entries[3].enabled, true);
    }
    void emptyAndCommentsOnly() {
        QCOMPARE(Mo2Importer::parseModlist("# comment\n\n").size(), 0);
    }
    void importStagesModsAndBuildsProfile() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        // MO2 mods dir with two mod folders (Data-relative content).
        write(mo2 + "/mods/Cool Textures/textures/a.dds", "tex");
        write(mo2 + "/mods/Cool Mod/meshes/b.nif", "mesh");
        // profile dir
        write(mo2 + "/profiles/Default/modlist.txt",
              "+Cool Mod\n+Textures_separator\n+Cool Textures\n");
        write(mo2 + "/profiles/Default/plugins.txt", "*Skyrim.esm\n*CoolMod.esp\n");

        QString staging = tmp.path() + "/staging";
        QString profilesRoot = tmp.path() + "/profiles";
        ProfileManager pm(profilesRoot);

        auto r = Mo2Importer::importProfile(
            mo2 + "/profiles/Default", mo2 + "/mods", staging, pm, "Imported", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());
        QCOMPARE(r.modsStaged, 2);

        Profile* p = pm.loadProfile("Imported");
        QVERIFY(p != nullptr);
        // 3 entries (2 mods + 1 separator), Solero order: Cool Textures(low), Textures sep, Cool Mod(high)
        QCOMPARE(p->modList().count(), 3);
        // Find the "Cool Textures" mod and verify its staged file is under Data/
        QString texId;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it)
            if (it->name == "Cool Textures") texId = it->id;
        QVERIFY(!texId.isEmpty());
        QVERIFY(QFile::exists(staging + "/" + texId + "/Data/textures/a.dds"));
        // plugins.txt imported (2 plugins)
        QCOMPARE(p->pluginList().count(), 2);
    }
    void usesLoadOrderTxtAndSeparatorColorAndCopyErrors() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        write(mo2 + "/mods/AAA/a.txt", "a");
        write(mo2 + "/mods/BBB/b.txt", "b");
        // Separator with a real MO2 @Variant(QColor) value -> #568abe.
        write(mo2 + "/mods/Sec_separator/meta.ini",
              "[General]\ncolor=@Variant(\\0\\0\\0\\x43\\x1\\xff\\xffVV\\x8a\\x8a\\xbe\\xbe\\0\\0)\n");
        write(mo2 + "/profiles/Default/modlist.txt", "+AAA\n+Sec_separator\n+BBB\n");
        // loadorder.txt drives order; plugins.txt drives enabled state.
        write(mo2 + "/profiles/Default/loadorder.txt", "Skyrim.esm\nAAA.esp\nBBB.esp\n");
        write(mo2 + "/profiles/Default/plugins.txt", "*Skyrim.esm\nBBB.esp\n");

        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importProfile(
            mo2 + "/profiles/Default", mo2 + "/mods",
            tmp.path() + "/staging", pm, "LO", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());

        Profile* p = pm.loadProfile("LO");
        QVERIFY(p != nullptr);
        // Plugin ORDER follows loadorder.txt (low->high == file top->bottom).
        QCOMPARE(p->pluginList().count(), 3);
        QCOMPARE(p->pluginList().at(0).filename, QString("Skyrim.esm"));
        QCOMPARE(p->pluginList().at(1).filename, QString("AAA.esp"));
        QCOMPARE(p->pluginList().at(2).filename, QString("BBB.esp"));
        // Enabled state from plugins.txt: Skyrim.esm(*) and BBB.esp(plain) on; AAA off.
        QCOMPARE(p->pluginList().at(0).enabled, true);
        QCOMPARE(p->pluginList().at(1).enabled, false);
        QCOMPARE(p->pluginList().at(2).enabled, true);
        // Separator picked up its colour from meta.ini.
        QString sepColor;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it)
            if (it->type == EntryType::Separator) sepColor = it->color;
        QCOMPARE(sepColor, QString("#568abe"));
    }
    void importInstanceSharesModsAcrossProfiles() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        // 3 unique mod folders (each with a dummy file).
        write(mo2 + "/mods/ModA/a.txt", "a");
        write(mo2 + "/mods/ModB/b.txt", "b");
        write(mo2 + "/mods/ModC/c.txt", "c");
        // P1: ModA, separator, ModB. (top=high)
        write(mo2 + "/profiles/P1/modlist.txt",
              "+ModB\n+Core_separator\n+ModA\n");
        write(mo2 + "/profiles/P1/plugins.txt", "*ModA.esp\n");
        // P2: ModC, ModB(disabled), ModA - different subset/order.
        write(mo2 + "/profiles/P2/modlist.txt",
              "+ModA\n-ModB\n+ModC\n");
        write(mo2 + "/profiles/P2/plugins.txt", "*ModC.esp\n");
        // selected_profile = P2.
        write(mo2 + "/ModOrganizer.ini",
              "[General]\nselected_profile=P2\n");

        QString staging = tmp.path() + "/staging";
        ProfileManager pm(tmp.path() + "/profiles");

        auto r = Mo2Importer::importInstance(mo2, staging, pm, "MyList", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());

        // 2 Solero profiles created with the MO2 names.
        QCOMPARE(r.profileNames.size(), 2);
        QVERIFY(r.profileNames.contains("P1"));
        QVERIFY(r.profileNames.contains("P2"));
        // primaryProfile maps to selected_profile P2.
        QCOMPARE(r.primaryProfile, QString("P2"));
        // 3 unique mods staged, not 5.
        QCOMPARE(r.modsStaged, 3);

        // ProfileManager keeps a SINGLE active profile, so capture everything we
        // need from P1 before loading P2 (which would invalidate the P1 pointer).
        QString p1ModA;
        {
            // P1: Solero order (low->high): ModA, Core sep, ModB.
            Profile* p1 = pm.loadProfile("P1");
            QVERIFY(p1 != nullptr);
            QCOMPARE(p1->modList().count(), 3);
            QCOMPARE(p1->modList().at(0).name, QString("ModA"));
            QCOMPARE(p1->modList().at(0).type, EntryType::Mod);
            QCOMPARE(p1->modList().at(1).type, EntryType::Separator);
            QCOMPARE(p1->modList().at(1).name, QString("Core"));
            QCOMPARE(p1->modList().at(2).name, QString("ModB"));
            p1ModA = p1->modList().at(0).id;
            // Plugins applied per-profile.
            QCOMPARE(p1->pluginList().count(), 1);
            QCOMPARE(p1->pluginList().at(0).filename, QString("ModA.esp"));
        }

        QString p2ModA;
        {
            // P2: Solero order (low->high): ModC, ModB(disabled), ModA.
            Profile* p2 = pm.loadProfile("P2");
            QVERIFY(p2 != nullptr);
            QCOMPARE(p2->modList().count(), 3);
            QCOMPARE(p2->modList().at(0).name, QString("ModC"));
            QCOMPARE(p2->modList().at(1).name, QString("ModB"));
            QCOMPARE(p2->modList().at(1).enabled, false);
            QCOMPARE(p2->modList().at(2).name, QString("ModA"));
            p2ModA = p2->modList().at(2).id;
            QCOMPARE(p2->pluginList().count(), 1);
            QCOMPARE(p2->pluginList().at(0).filename, QString("ModC.esp"));
        }

        // Shared staging: ModA has the same Solero id in both profiles.
        QVERIFY(!p1ModA.isEmpty());
        QCOMPARE(p1ModA, p2ModA);
        QVERIFY(QFile::exists(staging + "/" + p1ModA + "/Data/a.txt"));
        // Staged exactly once: only 3 dirs under staging.
        QCOMPARE(QDir(staging).entryList(QDir::Dirs | QDir::NoDotAndDotDot).size(), 3);
    }
    void capturesNexusIdAndVersionFromMetaIni() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        // Mod with a Nexus meta.ini.
        write(mo2 + "/mods/Better Weather/textures/a.dds", "tex");
        write(mo2 + "/mods/Better Weather/meta.ini",
              "[General]\ngameName=SkyrimSE\nmodid=12345\nversion=2.0\n"
              "installationFile=Better Weather-12345.7z\nrepository=Nexus\n");
        // Mod without a meta.ini.
        write(mo2 + "/mods/No Meta Mod/meshes/b.nif", "mesh");
        write(mo2 + "/profiles/Default/modlist.txt",
              "+Better Weather\n+No Meta Mod\n");

        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importProfile(
            mo2 + "/profiles/Default", mo2 + "/mods",
            tmp.path() + "/staging", pm, "Meta", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());

        Profile* p = pm.loadProfile("Meta");
        QVERIFY(p != nullptr);
        QString withId, withoutId, withVer;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it) {
            if (it->name == "Better Weather") { withId = it->nexusModId; withVer = it->version; }
            if (it->name == "No Meta Mod")     withoutId = it->nexusModId;
        }
        QCOMPARE(withId, QString("12345"));
        // FIX 4: "2.0" normalizes to "2" (trailing all-zero components stripped).
        QCOMPARE(withVer, QString("2"));
        QVERIFY(withoutId.isEmpty());
    }
    void skipsModGroupsArtifact() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        write(mo2 + "/mods/RealMod/a.txt", "a");
        // MO2's ModGroups metadata folder - not game content.
        write(mo2 + "/mods/ModGroups/group.modgroups", "{}");
        write(mo2 + "/mods/ModGroups/meta.ini", "[General]\n");
        write(mo2 + "/profiles/P1/modlist.txt",
              "+RealMod\n+ModGroups\n");
        write(mo2 + "/ModOrganizer.ini", "[General]\nselected_profile=P1\n");

        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importInstance(mo2, tmp.path() + "/staging", pm,
                                             "MyList", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());
        // ModGroups excluded from unique-staged count: only RealMod.
        QCOMPARE(r.modsStaged, 1);

        Profile* p = pm.loadProfile("P1");
        QVERIFY(p != nullptr);
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it)
            QVERIFY2(it->name.compare("ModGroups", Qt::CaseInsensitive) != 0,
                     "ModGroups artifact must not be imported as a mod");
    }
    void importInstanceSkipsListTitleSeparator() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        write(mo2 + "/mods/ModA/a.txt", "a");
        // modlist.txt has the redundant list-title header separator plus a real one.
        write(mo2 + "/profiles/P1/modlist.txt",
              "+ModA\n-Gameplay_separator\n-MyList 1.0_separator\n");
        write(mo2 + "/ModOrganizer.ini", "[General]\nselected_profile=P1\n");

        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importInstance(mo2, tmp.path() + "/staging", pm,
                                             "MyList", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());

        Profile* p = pm.loadProfile("P1");
        QVERIFY(p != nullptr);
        bool hasGameplay = false, hasListTitle = false;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it) {
            if (it->type != EntryType::Separator) continue;
            if (it->name == "Gameplay") hasGameplay = true;
            if (it->name.startsWith("MyList")) hasListTitle = true;
        }
        QVERIFY2(hasGameplay, "real Gameplay separator must be kept");
        QVERIFY2(!hasListTitle, "list-title separator must be skipped");
    }
    void classifiesRootVsDataContent() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        // Mod A: normal Data-relative meshes + a root ENB dll + a root .esp.
        write(mo2 + "/mods/ENB Mod/meshes/x.nif", "nif");
        write(mo2 + "/mods/ENB Mod/enbhost.dll", "dll");
        write(mo2 + "/mods/ENB Mod/Cool.esp", "esp");
        // Mod B: Root Builder layout (Root/d3dx9_42.dll).
        write(mo2 + "/mods/RootMod/Root/d3dx9_42.dll", "d3d");
        // Mod C: game-root-relative (has a Data/ subdir + a root loader.exe).
        write(mo2 + "/mods/RootRel/Data/Scripts/s.pex", "pex");
        write(mo2 + "/mods/RootRel/loader.exe", "exe");
        write(mo2 + "/profiles/Default/modlist.txt",
              "+ENB Mod\n+RootMod\n+RootRel\n");

        QString staging = tmp.path() + "/staging";
        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importProfile(
            mo2 + "/profiles/Default", mo2 + "/mods", staging, pm, "Cls", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());

        Profile* p = pm.loadProfile("Cls");
        QVERIFY(p != nullptr);
        QString enbId, rootId, relId;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it) {
            if (it->name == "ENB Mod") enbId = it->id;
            if (it->name == "RootMod") rootId = it->id;
            if (it->name == "RootRel") relId = it->id;
        }
        QVERIFY(!enbId.isEmpty() && !rootId.isEmpty() && !relId.isEmpty());
        // ENB Mod: root dll at root, meshes + esp under Data/.
        QVERIFY(QFile::exists(staging + "/" + enbId + "/enbhost.dll"));
        QVERIFY(QFile::exists(staging + "/" + enbId + "/Data/meshes/x.nif"));
        QVERIFY(QFile::exists(staging + "/" + enbId + "/Data/Cool.esp"));
        QVERIFY(!QFile::exists(staging + "/" + enbId + "/Data/enbhost.dll"));
        // RootMod: Root/d3dx9_42.dll -> root.
        QVERIFY(QFile::exists(staging + "/" + rootId + "/d3dx9_42.dll"));
        QVERIFY(!QFile::exists(staging + "/" + rootId + "/Data/d3dx9_42.dll"));
        // RootRel: has Data/ subdir -> entries placed AS-IS at root.
        QVERIFY(QFile::exists(staging + "/" + relId + "/Data/Scripts/s.pex"));
        QVERIFY(QFile::exists(staging + "/" + relId + "/loader.exe"));
    }
    void normalizesStoredVersions() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        auto verFor = [&](const QString& mod, const QString& ver) -> QString {
            write(mo2 + "/mods/" + mod + "/a.txt", "a");
            write(mo2 + "/mods/" + mod + "/meta.ini",
                  "[General]\nmodid=1\nrepository=Nexus\nversion=" + ver + "\n");
            return mod;
        };
        verFor("V1", "1.7.1.0");
        verFor("V2", "2.0.0.0");
        verFor("V3", "1.0.1");
        write(mo2 + "/profiles/Default/modlist.txt", "+V1\n+V2\n+V3\n");

        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importProfile(
            mo2 + "/profiles/Default", mo2 + "/mods",
            tmp.path() + "/staging", pm, "Ver", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());
        Profile* p = pm.loadProfile("Ver");
        QVERIFY(p != nullptr);
        QHash<QString, QString> got;
        for (auto it = p->modList().begin(); it != p->modList().end(); ++it)
            got.insert(it->name, it->version);
        QCOMPARE(got.value("V1"), QString("1.7.1"));
        QCOMPARE(got.value("V2"), QString("2"));
        QCOMPARE(got.value("V3"), QString("1.0.1"));
    }
    void importsManualInstallFilesAsMod() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        write(mo2 + "/mods/ModA/a.txt", "a");
        // The engine's manual-install folder with a game-root dll + Data content.
        write(mo2 + "/__Files Requiring Manual Install/foo.dll", "dll");
        write(mo2 + "/__Files Requiring Manual Install/Data/Scripts/x.pex", "pex");
        write(mo2 + "/profiles/P1/modlist.txt", "+ModA\n");
        write(mo2 + "/profiles/P2/modlist.txt", "+ModA\n");
        write(mo2 + "/ModOrganizer.ini", "[General]\nselected_profile=P1\n");

        QString staging = tmp.path() + "/staging";
        ProfileManager pm(tmp.path() + "/profiles");
        auto r = Mo2Importer::importInstance(mo2, staging, pm, "MyList", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());
        // ModA + Manual Install Files counted.
        QCOMPARE(r.modsStaged, 2);

        QString manualId;
        {
            Profile* p1 = pm.loadProfile("P1");
            QVERIFY(p1 != nullptr);
            // Manual Install Files is at index 0 (lowest priority / top of LO).
            QCOMPARE(p1->modList().at(0).name, QString("Manual Install Files"));
            QVERIFY(p1->modList().at(0).enabled);
            QVERIFY(p1->modList().at(0).nexusModId.isEmpty());
            manualId = p1->modList().at(0).id;
        }
        {
            Profile* p2 = pm.loadProfile("P2");
            QVERIFY(p2 != nullptr);
            QCOMPARE(p2->modList().at(0).name, QString("Manual Install Files"));
            // Shared once: same id across profiles.
            QCOMPARE(p2->modList().at(0).id, manualId);
        }
        // Staged: root dll at root, Data content under Data/.
        QVERIFY(QFile::exists(staging + "/" + manualId + "/foo.dll"));
        QVERIFY(QFile::exists(staging + "/" + manualId + "/Data/Scripts/x.pex"));
    }
    void importInstanceDisambiguatesNames() {
        QTemporaryDir tmp;
        QString mo2 = tmp.path() + "/MO2";
        write(mo2 + "/mods/ModA/a.txt", "a");
        write(mo2 + "/profiles/P1/modlist.txt", "+ModA\n");
        write(mo2 + "/ModOrganizer.ini", "[General]\nselected_profile=P1\n");

        ProfileManager pm(tmp.path() + "/profiles");
        // Pre-create a Solero profile named "P1" to force disambiguation.
        QVERIFY(pm.createProfile("P1"));

        auto r = Mo2Importer::importInstance(mo2, tmp.path() + "/staging", pm,
                                             "MyList", /*symlink*/false);
        QVERIFY2(r.success, r.errorMessage.toUtf8());
        QCOMPARE(r.profileNames.size(), 1);
        QCOMPARE(r.profileNames.first(), QString("P1 (MyList)"));
        QCOMPARE(r.primaryProfile, QString("P1 (MyList)"));
    }
};
QTEST_MAIN(TestMo2Importer)
#include "test_Mo2Importer.moc"
